language: python
python:
  - "3.5"
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install colorama
script:
  - coverage run -m unittest test_rpn
after_success:
  - coverage report
  - coveralls
